### ISSUE TITLE
🫧 Remove commented lines of code

### ISSUE THREAD

**Issue by bbbbbrie** [bbbbbrie/pastebin-bisque#24]
In `src/pastebin_bisque/cli.py`, there are a few lines of code that are commented out. These lines should be removed in order to clean up the code and make it easier to read. 

## 📋 TODOs

These three items need to be addressed:

- [x] [line 39](https://github.com/bbbbbrie/pastebin-bisque/blob/main/src/pastebin_bisque/cli.py#L39)
- [x] [line 57](https://github.com/bbbbbrie/pastebin-bisque/blob/main/src/pastebin_bisque/cli.py#L57)
- [x] [lines 153 and 154](https://github.com/bbbbbrie/pastebin-bisque/blob/main/src/pastebin_bisque/cli.py#L153-L154)

Each of the items above should be in a different commit. These three items can all be in the same PR.

**Comment by bbbbbrie** [comment]
@arshad-ml Thank you _very_ much for the contribution! Happy 🎃 Hacktoberfest! I merged your changes into the branch I have prepared for `v1.0.1` of `pastebin-bisque`. I plan to release towards the end of October. Your changes will go live then! 🚀  I will mark this issue **Closed**. 

🦄 Brie
