### ISSUE TITLE
🔍  Fix failing GitHub Actions: No matching distribution for soupsieve==2.5

### ISSUE THREAD

**Issue by bbbbbrie** [bbbbbrie/pastebin-bisque#27]
The Python 3.7 GitHub Actions are [currently ❌ failing](https://github.com/bbbbbrie/pastebin-bisque/actions/runs/6519484194/job/17706030967#step:5) with this error message:

```shell
ERROR: Ignored the following versions that require a different python version: 2.5 Requires-Python >=3.8
  py37-nocov: FAIL code 1 (7.30 seconds)
  evaluation failed :( (7.80 seconds)
ERROR: Could not find a version that satisfies the requirement soupsieve==2.5 (from versions: 0.4, 0.5, 0.5.1, 0.5.2, 0.5.3, 0.6, 1.0b1, 1.0b2, 1.0, 1.0.1, 1.0.2, 1.1, 1.2, 1.2.1, 1.3, 1.3.1, 1.4, 1.5, 1.6, 1.6.1, 1.6.2, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.8, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 2.0, 2.0.1, 2.1, 2.2, 2.2.1, 2.3, 2.3.1, 2.3.2, 2.3.2.post1, 2.4, 2.4.1)
ERROR: No matching distribution found for soupsieve==2.5

Error: Process completed with exit code 1.
```

## 📋 TODOs

- [ ] Investigate why this is failing
- [ ] Troubleshoot
- [ ] Analyze possible solutions
- [ ] Choose a solution and commit changes that implement the solution

**Note**: please open pull requests (PRs) against the `dev/v1.0.1` branch. That will ensure that your changes get merged when the new version of `pastebin-bisque` is released in late October at the end of 🎃 Hacktoberfest. 

🦄 Brie
